### ISSUE TITLE
Debian repo libvarnishapi-dev error

### ISSUE THREAD

**Issue by blindpet** [varnishcache/pkg-varnish-cache#14] opened 2016-02-29 09:59 UTC
After the 4.1.1 update I now get this error on a fresh install

```
The following packages have unmet dependencies:
 libvarnishapi-dev : Depends: libvarnishapi1 (= 4.1.1-1~jessie) but 4.1.1-4.1.1~jessie is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by fgsch** [comment] 2016-02-29 11:11
Cannot reproduce installing from scratch.

Please make sure apt is up to date.

**Comment by fgsch** [comment] 2016-02-29 11:13
Can you share the output of `dpkg -l | grep varnish`?

**Comment by blindpet** [comment] 2016-02-29 11:15
```
 sudo dpkg -l | grep varnish
ii  libvarnishapi1                 4.1.1-4.1.1~jessie          amd64        shared libraries for Varnish
ii  varnish                        4.1.1-4.1.1~jessie          amd64        state of the art, high-performance web accelerator
```

**Comment by lkarsten** [comment] 2016-02-29 11:52
This looks like the hard version requirement in the installed package with the erroneous version name.

Fix would be to build&publish a 4.1.1-5 which would be greater than 4.1.1-4.1.1, or wait until 4.1.2 is out later in the week.

**Comment by fgsch** [comment] 2016-02-29 12:02
Or for the time being just reinstall :-)

**Comment by blindpet** [comment] 2016-02-29 12:28
Same problem

`sudo apt-get remove varnish`

Even tried purging

`sudo apt-get remove varnish --purge`

Reinstalling
```
sudo apt-get clean
sudo apt-get update
apt-get install varnish libvarnishapi-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libvarnishapi-dev : Depends: libvarnishapi1 (= 4.1.1-1~jessie) but 4.1.1-4.1.1~jessie is to be installed
```

**Comment by fgsch** [comment] 2016-02-29 13:19
You need to remove both varnish and libvarnishapi1. 
Basically make sure `dpkg -l | grep varnish` doesn't show anything before installing again.

**Comment by blindpet** [comment] 2016-02-29 13:21
I just built from source instead, this way I can use the init.d and /etc/default/varnish file so when I upgrade I won't have to update the varnish.service file to use the port I choose

**Comment by fgsch** [comment] 2016-02-29 13:22
Your call. You shouldn't need to update varnish.service if you do it correctly.

**Comment by blindpet** [comment] 2016-02-29 14:25
All I did was update the file /lib/systemd/system/varnish.service

and changed this line

`ExecStart=/usr/sbin/varnishd -a :80 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
`
It was overwritten when I udpated, what is the correct method?

**Comment by tfheen** [comment] 2016-02-29 20:55
]] blindpet 

> All I did was update the file /lib/systemd/system/varnish.service

Never change files in /lib by hand.

> ExecStart=/usr/sbin/varnishd -a :80 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
> 
> It was overwritten when I udpated, what is the correct method?

Drop that line into /etc/systemd/system/varnish.service.d/local.conf
instead.  Look for systemd snippets for guidance on how to use this.

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by blindpet** [comment] 2016-02-29 21:11
Thank you very much, in case somebody else stumbles upon this

Change the Varnish systemd service to use port 80

```
sudo mkdir -p /etc/systemd/system/varnish.service.d
sudo nano /etc/systemd/system/varnish.service.d/local.conf
```
Paste these lines (thanks to the Arch page)

```
[Service]
ExecStart=
ExecStart=/usr/sbin/varnishd -a :80 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
```

**Comment by fgsch** [comment] 2016-02-29 22:42
Or just `systemctl edit varnish`.

**Comment by blindpet** [comment] 2016-02-29 22:44
Thanks @fgsch I script everything so I'm assuming the local.conf method lends itself better to my needs

**Comment by fgsch** [comment] 2016-03-21 14:46
This was a transient error due to a glitch in the published packages and has been corrected since then. Closing.

**Closed by fgsch** 2016-03-21 14:46 UTC
