### ISSUE TITLE
Varnish does not return a success during systemd forking

### ISSUE THREAD

**Issue by Clorith** [varnishcache/pkg-varnish-cache#88] opened 2017-09-17 10:33 UTC
Varnish 4.1.8
Ubuntu 16.04 (4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

Varnish installed from apt via https://packagecloud.io/varnishcache/varnish41

---

The default startup type for systemd from 4.1.8 on Ubuntu 16.04 is `Type=fork`, systemd expects a form of success result from the process to know that the child has been created as expected.

Since this is never sent the process is left until the default systemd timeout period is exceeded, systemd then terminates the child that was created presuming it did not start cleanly.
Varnish does start as expected during this time, as you can hit the cache while waiting for the systemd timeout to be exceeded.

Setting `Type=simple` bypases this check and lets varnish start as expected.

Using `simple` also means failure checks are bypassed, so a success rsponse should be introduced.

**Comment by karlvr** [comment] 2018-02-21 21:01
I have encountered the same issue. My problem was that I had `-F` on the varnishd command line arguments. I apparently needed that in my previous setup, and I duplicated it here. That caused varnishd not to fork, and therefore `Type=forking` was inappropriate! With the `-F` removed the systemd script works perfectly.

**Comment by Dridi** [comment] 2018-02-21 23:26
Starting with Varnish 5 I'd recommend dropping the `varnishd -F` option and restoring the `Type=forking` property. Because Eric (yes, the demonologist) will ensure that the daemon's parent process exits precisely when the setup is over, other services depending on Varnish like `varnishlog.service` would only start when it's ready.

Tools like `varnishlog` work around the pre-Eric startup by implementing a 5s timeout by default to connect to the shared memory, so depending on _what_ service depends on Varnish it may not be a problem as long as `varnishd` takes less than 5s to finish setting up things (hint: a very large VCL could take seconds to compile).

**Comment by gquintard** [comment] 2018-02-22 10:25
@dridi, so, I totally agree with you, and I even reported that to the Arch bug tracker (https://bugs.archlinux.org/task/57598) but got refused as "unning daemons in the foreground is the normal and preferred way with systemd. There's nothing to do here.", so I'd be interested in knowing what the other distributions think.

**Comment by Dridi** [comment] 2018-02-22 10:32
Fedora has guidelines, so nothing is set in stone. You must follow them or ask for an exception if you can justify why the guidelines shouldn't apply to your case. I don't remember any guideline about daemons vs systemd, but `varnish.service` is forking.

**Comment by Dridi** [comment] 2018-02-27 15:37
@Clorith @karlvr

Any hints on how to reproduce this? We only had two reports of `varnishd` daemonizing and timing out in systemd.

**Comment by Clorith** [comment] 2018-02-27 20:17
I only experienced it on the one box I have varnish on, but it was an update from 4.1.6 to 4.1.8. I'm afraid I don't recall much more about it than that, the update was performed using `aptitude safe-upgrade`

**Comment by Dridi** [comment] 2018-02-27 21:08
I have a lead, can you confirm that you are running with a `-j unix` option (or no `-j` option at all) in your `varnishd` command line?

If yes, does it still happen if you use `-j none` instead?

I was able to reproduce the following scenario:

- start the service
- hang for 30s
- service properly started

The stall happens when `varnishd` tries to look up its own credentials, and fiddling with my network stack I was able to slow this down long enough to look like I reached some systemd timeout whereas systemd was actually happily waiting for the daemonizing process to exit.

**Comment by Dridi** [comment] 2018-02-27 21:16
Basically it looks like this:

```
$ time sudo systemctl start varnish && sudo systemctl status varnish

real	0m30.359s
user	0m0.014s
sys	0m0.010s
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/etc/systemd/system/varnish.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-02-27 22:13:26 CET; 23ms ago
  Process: 18933 ExecStart=/usr/sbin/varnishd [...]
 Main PID: 18934 (varnishd)
    Tasks: 218 (limit: 4915)
   CGroup: /system.slice/varnish.service
           ├─18934 /usr/sbin/varnishd [...]
           └─18947 /usr/sbin/varnishd [...]

Feb 27 22:12:55 varnish systemd[1]: Starting Varnish Cache, a high-performance HTTP accelerator...
Feb 27 22:13:25 varnish varnishd[18933]: Debug: Platform: Linux,[...],-junix,-smalloc,-smalloc,-hcritbit
Feb 27 22:13:25 varnish varnishd[18934]: Platform: Linux,[...],-junix,-smalloc,-smalloc,-hcritbit
Feb 27 22:13:25 varnish varnishd[18933]: Debug: Child (18947) Started
Feb 27 22:13:25 varnish varnishd[18934]: Child (18947) Started
Feb 27 22:13:26 varnish varnishd[18934]: Child (18947) said Child starts
Feb 27 22:13:26 varnish systemd[1]: Started Varnish Cache, a high-performance HTTP accelerator.
```

**Comment by Dridi** [comment] 2018-04-30 09:44
@Clorith, can you still reproduce this behavior and confirm that disabling the unix jail (`-j none`) removes this behavior? I have no other lead and would like to close this issue with a docfix if you can confirm my observations on your system.

**Comment by Clorith** [comment] 2018-05-03 08:37
Hi,

Apologies, I didn't notice the notification here for the previous updates.

Yes varnishd runs with a `-j unix` at this time when it starts up as expected. Unfortunately I don't have a test system available at this time for testing what was proposed, but it makes sense that it may be related. If you don't mind I can roll a test this weekend to confirm.

**Comment by Dridi** [comment] 2018-05-03 08:53
No worries and no hurry, my last comment was just routine inspection of our open tickets.

And thank you for taking the time to confirm.

**Comment by Clorith** [comment] 2018-06-04 02:57
I'm no longer able to replicate the issue above 👍

**Comment by Dridi** [comment] 2018-06-04 08:27
Very recently on Fedora I was at least able to figure the reason of the hang depending on my nsswitch configuration and could blame the global SELinux policy missing a permission with the help of a couple people:

https://bugzilla.redhat.com/show_bug.cgi?id=1584632

I see no reason to keep this open, thanks for the feedback!

**Comment by gregnetau** [comment] 2018-06-04 08:33
This still occurs for me on two fresh installs @Dridi. Works fine from this command line

`varnishd -F -f /etc/varnish/default.vcl -a 127.0.0.1:8181,PROXY -a 10.200.7.221:8080 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -p feature=+http2 -s malloc,6G -s file,/cache/varnish/cache1.bin,192G -t 86400`

Does not work with init.d:

root@sjc-cache1:~# /etc/init.d/varnish start
[....] Starting varnish (via systemctl): varnish.serviceJob for varnish.service failed because a timeout was exceeded. See "systemctl status varnish.service" and "journalctl -xe" for details.
 failed!
root@sjc-cache1:~# systemctl status varnish.service
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/varnish.service.d
           └─customexec.conf
   Active: failed (Result: timeout) since Mon 2018-06-04 01:32:29 PDT; 18s ago
  Process: 619 ExecStart=/usr/sbin/varnishd -F -a 127.0.0.1:8181,PROXY -a 10.200.7.221:8080 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -p feature=+http2 -s mallo
 Main PID: 31540 (code=exited, status=0/SUCCESS)

```
Jun 04 01:32:28 sjc-cache1 varnishd[619]: Debug: Stopping Child
Jun 04 01:32:28 sjc-cache1 varnishd[619]: Manager got SIGINT
Jun 04 01:32:28 sjc-cache1 varnishd[619]: Stopping Child
Jun 04 01:32:29 sjc-cache1 varnishd[619]: Child (632) died signal=15
Jun 04 01:32:29 sjc-cache1 varnishd[619]: Error: Child (632) died signal=15
Jun 04 01:32:29 sjc-cache1 varnishd[619]: Debug: Child cleanup complete
Jun 04 01:32:29 sjc-cache1 varnishd[619]: Child cleanup complete
Jun 04 01:32:29 sjc-cache1 systemd[1]: Failed to start Varnish Cache, a high-performance HTTP accelerator.
Jun 04 01:32:29 sjc-cache1 systemd[1]: varnish.service: Unit entered failed state.
Jun 04 01:32:29 sjc-cache1 systemd[1]: varnish.service: Failed with result 'timeout'.

```

**Comment by Dridi** [comment] 2018-06-04 08:50
Hi, what's the content of `/etc/systemd/system/varnish.service.d/customexec.conf`?

**Comment by gregnetau** [comment] 2018-06-04 10:05
```
root@sjc-cache1:/etc/systemd/system/varnish.service.d# cat customexec.conf
[Service]
ExecStart=
ExecStart=/usr/sbin/varnishd -F -a 127.0.0.1:8181,PROXY -a 10.200.7.221:8080 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret  -p feature=+http2 -s malloc,6G -s file,/cache/varnish/cache1.bin,128G -t -t 86400

```

**Comment by Dridi** [comment] 2018-06-04 10:11
If you are using our packages, you should not put `-F` in your command line. Unless you modified `/lib/systemd/system/varnish.service` which I find highly unlikely since you set up an override.

**Comment by gregnetau** [comment] 2018-06-04 10:17
Thanks - confirming removing the "-F" from my customexec has fixed the issue!

**Closed** 2018-06-04 10:54 UTC
Labels: invalid

**Comment by abdulrafaywaqar** [comment] 2025-03-09 23:26
Mar 09 22:46:56 ip-10-0-1-4 varnishd[221351]: Error: Manager got SIGTERM
Mar 09 22:46:56 ip-10-0-1-4 varnishd[221351]: Debug: Stopping Child
Mar 09 22:46:56 ip-10-0-1-4 varnishd[221351]: Manager got SIGTERM
Mar 09 22:46:56 ip-10-0-1-4 varnishd[221351]: Stopping Child
Mar 09 22:46:56 ip-10-0-1-4 systemd[1]: Stopping varnish.service - Varnish Cache, a high-performance HTTP accelerator...
Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Error: Child (221373) died signal=15
Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Child (221373) died signal=15
Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Debug: Child cleanup complete
Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Child cleanup complete
Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Info: manager stopping child
Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Info: manager dies
Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: manager stopping child
Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: manager dies
Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: varnish.service: Main process exited, code=exited, status=64/USAGE
Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: varnish.service: Failed with result 'exit-code'.
Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: Stopped varnish.service - Varnish Cache, a high-performance HTTP accelerator.
Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: varnish.service: Consumed 1d 2h 18min 33.057s CPU time.
Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: Started varnish.service - Varnish Cache, a high-performance HTTP accelerator.
Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Debug: Version: varnish-7.1.1 revision 7cee1c581bead20e88d101ab3d72afb29f14d87a
Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Debug: Platform: Linux,6.8.0-1021-aws,x86_64,-junix,-smalloc,-sdefault,-hcritbit
Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Version: varnish-7.1.1 revision 7cee1c581bead20e88d101ab3d72afb29f14d87a
Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Platform: Linux,6.8.0-1021-aws,x86_64,-junix,-smalloc,-sdefault,-hcritbit
Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Debug: Child (232667) Started
Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Child (232667) Started
Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Child launched OK
Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Info: Child (232667) said Child starts
Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Child (232667) said Child starts

**Comment by abdulrafaywaqar** [comment] 2025-03-09 23:27
> Mar 09 22:46:56 ip-10-0-1-4 varnishd[221351]: Error: Manager got SIGTERM Mar 09 22:46:56 ip-10-0-1-4 varnishd[221351]: Debug: Stopping Child Mar 09 22:46:56 ip-10-0-1-4 varnishd[221351]: Manager got SIGTERM Mar 09 22:46:56 ip-10-0-1-4 varnishd[221351]: Stopping Child Mar 09 22:46:56 ip-10-0-1-4 systemd[1]: Stopping varnish.service - Varnish Cache, a high-performance HTTP accelerator... Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Error: Child (221373) died signal=15 Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Child (221373) died signal=15 Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Debug: Child cleanup complete Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Child cleanup complete Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Info: manager stopping child Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: Info: manager dies Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: manager stopping child Mar 09 22:46:57 ip-10-0-1-4 varnishd[221351]: manager dies Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: varnish.service: Main process exited, code=exited, status=64/USAGE Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: varnish.service: Failed with result 'exit-code'. Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: Stopped varnish.service - Varnish Cache, a high-performance HTTP accelerator. Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: varnish.service: Consumed 1d 2h 18min 33.057s CPU time. Mar 09 22:46:57 ip-10-0-1-4 systemd[1]: Started varnish.service - Varnish Cache, a high-performance HTTP accelerator. Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Debug: Version: varnish-7.1.1 revision 7cee1c581bead20e88d101ab3d72afb29f14d87a Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Debug: Platform: Linux,6.8.0-1021-aws,x86_64,-junix,-smalloc,-sdefault,-hcritbit Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Version: varnish-7.1.1 revision 7cee1c581bead20e88d101ab3d72afb29f14d87a Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Platform: Linux,6.8.0-1021-aws,x86_64,-junix,-smalloc,-sdefault,-hcritbit Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Debug: Child (232667) Started Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Child (232667) Started Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Child launched OK Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Info: Child (232667) said Child starts Mar 09 22:46:58 ip-10-0-1-4 varnishd[232644]: Child (232667) said Child starts

We are usinig varnish with Magento and all of a sudden the varnish down and we are getting 504.
These are the error logs
