### ISSUE TITLE
Varnish Update fails on start of varnishncsa and varnishlog

### ISSUE THREAD

**Issue by dunkla** [varnishcache/pkg-varnish-cache#55] opened 2016-12-07 15:58 UTC
Running debian the postinst tries to start
- varnish
- varnishncsa
- varnishlog

All service are installed but disabled by default. (in /etc/default/*)
varnish will "start" just fine because of
```
        case "${START:-}" in
            [Yy]es|[Yy]|1|[Tt]|[Tt]rue)
                start_varnishd
                ;;
            *)
                disabled_varnishd
                ;;
        esac
```
in the corresponding init.d file, but varnishncsa and varnishlog respectively do not have this check. This leads to a failed upgrade because varnishncsa and varnishlog expect varnish running. 

Both service will have to have a check too, or the postinst shouldn't be trying to start them, if varnish isn't running.

**Comment by denisbr** [comment] 2016-12-08 09:36
Could you add a bit more information?
* package version and release
* OS distribution and version

**Comment by dunkla** [comment] 2016-12-08 09:57
- Debian 8.6 (Jessie)
- trying to upgrade from 4.1.3-1~jessie to 4.1.4

**Comment by denisbr** [comment] 2016-12-13 11:54
The ``varnishlog`` service is no longer part of this package, but I have added checks for disabled status to the ``varnishncsa`` service in 8379aae2650a5b27d38d416cb1f7fbceb779b3b9.

**Comment by denisbr** [comment] 2016-12-13 12:42
@dunkla Can you test the new version (4.1.4-2) and see if it improves the situation?

**Comment by dunkla** [comment] 2016-12-13 13:24
@denisbr Tried it and failed again. I think i missed the point that Debian 8 uses systemd. Does the binary have to respect the option too? The systemd file (/lib/systemd/system/varnishncsa.service) uses:
`ExecStart=/usr/bin/varnishncsa -a -w /var/log/varnish/varnishncsa.log -D -P /run/varnishncsa/varnishncsa.pid`

**Comment by denisbr** [comment] 2016-12-13 13:29
@dunkla Ah, ok, I'll test more, thanks.

**Comment by denisbr** [comment] 2016-12-13 14:08
I tried to reproduce your problem, but I failed. @dunkla could you please describe in detail how you encounter the problem (preferably with some output showing the problem)?

**Comment by dunkla** [comment] 2016-12-13 14:31
```
root@srv-a-de:/# apt-cache policy varnish
varnish:
  Installed: 4.1.3-1~jessie
  Candidate: 4.1.4-3~jessie
```

```
root@srv-a-de:/# apt-get install varnish
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  varnish-dev
The following packages will be REMOVED:
  libvarnishapi1
The following packages will be upgraded:
  varnish
1 upgraded, 0 newly installed, 1 to remove and 43 not upgraded.
Need to get 2399 kB of archives.
After this operation, 4098 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://repo.varnish-cache.org/debian/ jessie/varnish-4.1 varnish amd64 4.1.4-3~jessie [2399 kB]
Fetched 2399 kB in 0s (3526 kB/s)
dpkg: libvarnishapi1: dependency problems, but removing anyway as you requested:
 varnish depends on libvarnishapi1 (= 4.1.3-1~jessie).

(Reading database ... 37605 files and directories currently installed.)
Removing libvarnishapi1 (4.1.3-1~jessie) ...
Processing triggers for libc-bin (2.19-18+deb8u6) ...
(Reading database ... 37601 files and directories currently installed.)
Preparing to unpack .../varnish_4.1.4-3~jessie_amd64.deb ...
Unpacking varnish (4.1.4-3~jessie) over (4.1.3-1~jessie) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u5) ...
Setting up varnish (4.1.4-3~jessie) ...
Installing new version of config file /etc/init.d/varnishncsa ...
Installing new version of config file /etc/logrotate.d/varnish ...
Job for varnishncsa.service failed. See 'systemctl status varnishncsa.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript varnishncsa, action "start" failed.
dpkg: error processing package varnish (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (215-17+deb8u5) ...
Errors were encountered while processing:
 varnish
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The log says:
```
Dec 13 15:26:47 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:47 srv-a-de systemd[1]: Stopped Varnish Cache HTTP accelerator NCSA logging daemon.
Dec 13 15:26:47 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:47 srv-a-de systemd[1]: Stopped Varnish Cache HTTP accelerator logging daemon.
Dec 13 15:26:47 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:47 srv-a-de systemd[1]: Stopped Varnish Cache, a high-performance HTTP accelerator.
Dec 13 15:26:48 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:48 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:48 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:49 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:50 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:50 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:50 srv-a-de systemd[1]: Starting Varnish Cache, a high-performance HTTP accelerator...
Dec 13 15:26:50 srv-a-de varnish[9309]: Not starting HTTP accelerator: varnish disabled in /etc/default/varnish.
Dec 13 15:26:50 srv-a-de systemd[1]: Started Varnish Cache, a high-performance HTTP accelerator.
Dec 13 15:26:50 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:50 srv-a-de systemd[1]: Reloading.
Dec 13 15:26:50 srv-a-de systemd[1]: Starting Varnish Cache HTTP accelerator NCSA logging daemon...
Dec 13 15:26:50 srv-a-de varnishncsa[9359]: Can't open log - retrying for 5 seconds
Dec 13 15:26:55 srv-a-de varnishncsa[9359]: Can't open VSM file (Abandoned VSM file (Varnish not running?) /var/lib/varnish/srv-a-de/_.vsm
Dec 13 15:26:55 srv-a-de varnishncsa[9359]: )
Dec 13 15:26:55 srv-a-de systemd[1]: varnishncsa.service: control process exited, code=exited status=1
Dec 13 15:26:55 srv-a-de systemd[1]: Failed to start Varnish Cache HTTP accelerator NCSA logging daemon.
Dec 13 15:26:55 srv-a-de systemd[1]: Unit varnishncsa.service entered failed state.
Dec 13 15:26:55 srv-a-de systemd[1]: Reloading.
```

Is this enough information?

**Comment by denisbr** [comment] 2016-12-13 14:54
Thanks, what is the contents of your /etc/default/varnish ?

**Comment by dunkla** [comment] 2016-12-13 15:26
```
# Configuration file for Varnish Cache.
#
# /etc/init.d/varnish expects the variables $DAEMON_OPTS, $NFILES and $MEMLOCK
# to be set from this shell script fragment.
#
# Note: If systemd is installed, this file is obsolete and ignored.  You will
# need to copy /lib/systemd/system/varnish.service to /etc/systemd/system/ and
# edit that file.

# Should we start varnishd at boot?  Set to "no" to disable.
START=no

# Maximum number of open files (for ulimit -n)
NFILES=131072

# Maximum locked memory size (for ulimit -l)
# Used for locking the shared memory log in memory.  If you increase log size,
# you need to increase this number as well
MEMLOCK=82000

DAEMON_OPTS="-a :80 \
             -T localhost:6082 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -s malloc,256m"

```

```
# Configuration file for varnishncsa
#
# This shell script fragment is sourced by /etc/init.d/varnishncsa
#
# Note: If systemd is installed, this file is obsolete and ignored.  You will
# need to copy /lib/systemd/system/varnishncsa.service to /etc/systemd/system/
# and edit that file.
#
# Uncomment this to enable logging for varnish.  Please make sure you have
# enough disk space for significant amounts of log data.  To disable logging,
# set the variable to "0", "no", or leave it unset.
#
# NCSA log format, to be used by HTTP log analyzers
# VARNISHNCSA_ENABLED=1
#
# If you want to add more arguments to varnishncsa, such as providing
# a different log format, you can override the DAEMON_OPTS variable
# from /etc/init.d/varnishncsa here.
# DAEMON_OPTS="-a -w ${LOGFILE} -D -P ${PIDFILE}"
```

**Comment by denisbr** [comment] 2016-12-13 22:00
I have tried again to reproduce the problem, but I am unsuccessful. Clean debian 8 install, first installed varnish 4.1.3-1~jessie, then made sure the configfiles matched yours, and finally apt-get install varnish, or even apt-get dist-upgrade. Both work fine.

I see the reason this fails in your log, varnishncsa fails due to varnishd not starting (with the message ``Not starting HTTP accelerator: varnish disabled in /etc/default/varnish.``). However, when I have ``START=no`` in my ``/etc/default/varnish`` the service starts anyway (as you say the systemd service doesn't use that file).

Not sure what is different on your system, but with that information, maybe you have something more to go on when looking for anything out of the ordinary?

Do you have any local changes to the systemd service files? (/lib/systemd/system/varnish.service, /lib/systemd/system/varnishncsa.service) or anything init-related?

**Comment by dunkla** [comment] 2016-12-14 11:02
Further testing showed following behavior:

1. /etc/default/varnish:START=yes; systemctl start varnish => varnish started
2. /etc/default/varnish:START=yes; systemctl stop varnish => varnish stopped
3. /etc/default/varnish:START=no; systemctl start varnish => varnish NOT started (no listen entry in ``netstat -tulpn`` and no entry in the process list)
4. /etc/default/varnish:START=yes; systemctl start varnish => varnish still not started
5. /etc/default/varnish:START=yes; systemctl stop varnish;  systemctl start varnish => varnish started

Therefore i conclude, that
1. ``systemctl start varnish`` does somehow take ``/etc/default/varnish`` into account
2. somewhere there is a state, which is wrong (varnish not starting again if there was no stop before, even if the service did not start correctly). I pin this behavior on the combination of systemd and varnish (varnish not starting because it's disabled, but exiting without failure)

Referring to you answer: Varnish does not start, when START=no. I cannot reproduce varnish starting if start=no. Therefore varnishncsa shouldn't either. I am not sure yet how to proceed further.

**Comment by denisbr** [comment] 2016-12-14 12:13
Still cannot reproduce on my testbed: 

First, ``START=yes``:

```
root@debian-8-org:~# apt-cache policy varnish
varnish:
  Installed: 4.1.3-1~jessie
  Candidate: 4.1.4-3~jessie
  Version table:
     4.1.4-3~jessie 0
        500 file:/vagrant/provision/repo/deb/8/ ./ Packages
 *** 4.1.3-1~jessie 0
        100 /var/lib/dpkg/status
     4.0.2-1 0
        500 http://ftp.de.debian.org/debian/ jessie/main amd64 Packages
root@debian-8-org:~# vim /etc/default/varnish
root@debian-8-org:~# grep START /etc/default/varnish
START=yes
root@debian-8-org:~# systemctl start varnish
root@debian-8-org:~# systemctl status varnish
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; disabled)
   Active: active (running) since Wed 2016-12-14 13:07:06 CET; 56s ago
 Main PID: 7861 (varnishd)
   CGroup: /system.slice/varnish.service
           ├─7861 /usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
           └─7863 /usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m

Dec 14 13:07:06 debian-8-org systemd[1]: Started Varnish Cache, a high-performance HTTP accelerator.
Dec 14 13:07:06 debian-8-org varnishd[7861]: Platform: Linux,3.16.0-4-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Dec 14 13:07:06 debian-8-org varnishd[7861]: Child (7863) Started
Dec 14 13:07:07 debian-8-org varnishd[7861]: Child (7863) said Child starts
Dec 14 13:07:58 debian-8-org systemd[1]: Started Varnish Cache, a high-performance HTTP accelerator.
root@debian-8-org:~# systemctl stop varnish
root@debian-8-org:~# systemctl status varnish
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; disabled)
   Active: inactive (dead) since Wed 2016-12-14 13:08:13 CET; 2s ago
 Main PID: 7861 (code=exited, status=0/SUCCESS)

Dec 14 13:07:06 debian-8-org systemd[1]: Started Varnish Cache, a high-performance HTTP accelerator.
Dec 14 13:07:06 debian-8-org varnishd[7861]: Platform: Linux,3.16.0-4-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Dec 14 13:07:06 debian-8-org varnishd[7861]: Child (7863) Started
Dec 14 13:07:07 debian-8-org varnishd[7861]: Child (7863) said Child starts
Dec 14 13:07:58 debian-8-org systemd[1]: Started Varnish Cache, a high-performance HTTP accelerator.
Dec 14 13:08:12 debian-8-org systemd[1]: Stopping Varnish Cache, a high-performance HTTP accelerator...
Dec 14 13:08:12 debian-8-org varnishd[7861]: Manager got SIGINT
Dec 14 13:08:12 debian-8-org varnishd[7861]: Stopping Child
Dec 14 13:08:13 debian-8-org systemd[1]: Stopped Varnish Cache, a high-performance HTTP accelerator.
```

Then modifying ``/etc/default/varnish``: 

```
root@debian-8-org:~# vim /etc/default/varnish
root@debian-8-org:~# grep START /etc/default/varnish
START=no
root@debian-8-org:~# systemctl start varnish
root@debian-8-org:~# systemctl status varnish
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; disabled)
   Active: active (running) since Wed 2016-12-14 13:08:43 CET; 3s ago
  Process: 9748 ExecStart=/usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m (code=exited, status=0/SUCCESS)
 Main PID: 9758 (varnishd)
   CGroup: /system.slice/varnish.service
           ├─9758 /usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
           └─9759 /usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m

Dec 14 13:08:43 debian-8-org systemd[1]: Starting Varnish Cache, a high-performance HTTP accelerator...
Dec 14 13:08:43 debian-8-org systemd[1]: Started Varnish Cache, a high-performance HTTP accelerator.
Dec 14 13:08:43 debian-8-org varnishd[9758]: Platform: Linux,3.16.0-4-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Dec 14 13:08:43 debian-8-org varnishd[9758]: Child (9759) Started
Dec 14 13:08:43 debian-8-org varnishd[9758]: Child (9759) said Child starts
root@debian-8-org:~# systemctl stop varnish
root@debian-8-org:~# systemctl status varnish
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; disabled)
   Active: inactive (dead) since Wed 2016-12-14 13:08:58 CET; 51s ago
  Process: 9748 ExecStart=/usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m (code=exited, status=0/SUCCESS)
 Main PID: 9758 (code=exited, status=0/SUCCESS)

Dec 14 13:08:43 debian-8-org systemd[1]: Starting Varnish Cache, a high-performance HTTP accelerator...
Dec 14 13:08:43 debian-8-org systemd[1]: Started Varnish Cache, a high-performance HTTP accelerator.
Dec 14 13:08:43 debian-8-org varnishd[9758]: Platform: Linux,3.16.0-4-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Dec 14 13:08:43 debian-8-org varnishd[9758]: Child (9759) Started
Dec 14 13:08:43 debian-8-org varnishd[9758]: Child (9759) said Child starts
Dec 14 13:08:57 debian-8-org systemd[1]: Stopping Varnish Cache, a high-performance HTTP accelerator...
Dec 14 13:08:57 debian-8-org varnishd[9758]: Manager got SIGINT
Dec 14 13:08:57 debian-8-org varnishd[9758]: Stopping Child
Dec 14 13:08:58 debian-8-org varnishd[9758]: Child (9759) died signal=15
Dec 14 13:08:58 debian-8-org systemd[1]: Stopped Varnish Cache, a high-performance HTTP accelerator.
```

Based on this, I'm pretty confident that there is something else going on on your system. Could it be left-over initscripts from a different packaged version of varnish? I've seen things like this when both systemd and initscripts were installed for some daemons.

**Comment by dunkla** [comment] 2016-12-14 13:40
Well, it seems i found the culprit. Because varnish through systemd doesn't respect /etc/default/varnish, we fixed it for us with an own script a while ago. I did the same for varnishncsa now:
```
[Unit]
Description=Varnish Cache HTTP accelerator NCSA logging daemon
After=varnish.service

[Service]
Type=oneshot
ExecStart=/etc/init.d/varnishncsa start
ExecStop=/etc/init.d/varnishncsa stop
ExecStatus=/etc/init.d/varnishncsa status
ExecReload=/etc/init.d/varnishncsa reload
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```
This coupled with your fixes regarding VARNISHNCSA_ENABLED to the init.d file allows for a smooth update.

Are there any plans on using the /etc/default/* files in your systemd units?

On an unrelated note, why is libvarnishapi1 removed?

Anyway, thank you very much for you quick and immense help. This was rather refreshing.

**Comment by denisbr** [comment] 2016-12-15 10:25
Good to hear you found the issue.

As far as I know, ``/etc/default/`` files are not a systemd-ism, and I don't think we will use those going forward.

The package ``libvarnishapi1`` is removed, but the contents of that package has now been merged into the ``varnish`` package. 

I'm happy this was sorted out, and that the package metadata now seems to be working as intended.

**Closed by denisbr** 2016-12-15 10:25 UTC
