### ISSUE TITLE
Ubuntu14.04 varnish5.1 service restart fails

### ISSUE THREAD

**Issue by RyanJarv** [varnishcache/pkg-varnish-cache#75] opened 2017-04-17 01:18 UTC
Not sure if this is a change to varnish and the init.d script needs to be updated or something else.

Currently getting the following error when running `service varnish restart` on Ubuntu 14.04 with varnish 5.1.
```vagrant@varnish51-ubuntu-1404:~$ sudo service varnish restart
 * Checking syntax varnishd                                                                                                                                              [fail] 
Error: Could not get socket 0.0.0.0:6081: Address already in use
(-? gives usage)
 * Syntax check failed, not restarting
```

Checking the config manually on Ubuntu 14.04 Varnish 5.1:
```
vagrant@varnish51-ubuntu-1404:~$ varnishd -V
varnishd (varnish-5.1.2 revision 6ece695)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
vagrant@varnish51-ubuntu-1404:~$ sudo lsof -i -n |grep LISTEN
rpcbind     543    root    8u  IPv4   9103      0t0  TCP *:sunrpc (LISTEN)
rpcbind     543    root   11u  IPv6   9106      0t0  TCP *:sunrpc (LISTEN)
rpc.statd   593   statd    9u  IPv4   9191      0t0  TCP *:51088 (LISTEN)
rpc.statd   593   statd   11u  IPv6   9197      0t0  TCP *:60452 (LISTEN)
sshd       1008    root    3u  IPv4   9871      0t0  TCP *:ssh (LISTEN)
sshd       1008    root    4u  IPv6   9873      0t0  TCP *:ssh (LISTEN)
varnishd  14754 varnish    3u  IPv4  28667      0t0  TCP *:6081 (LISTEN)
varnishd  14754 varnish    6u  IPv4  28678      0t0  TCP 127.0.0.1:6082 (LISTEN)
cache-mai 14762  vcache    3u  IPv4  28667      0t0  TCP *:6081 (LISTEN)
vagrant@varnish51-ubuntu-1404:~$ sudo /usr/sbin/varnishd -a 0.0.0.0:6081 -T 127.0.0.1:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m -C -n /tmp 2>&1|head
Error: Could not get socket 0.0.0.0:6081: Address already in use
(-? gives usage)
```

This works as expected on Ubuntu 14.04 Varnish 4.1:
```
vagrant@varnish41-ubuntu-1404:~$ varnishd -V
varnishd (varnish-4.1.5 revision 2c82b1c)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
vagrant@varnish41-ubuntu-1404:~$ sudo lsof -i -n |grep LISTEN
rpcbind     552    root    8u  IPv4   9103      0t0  TCP *:sunrpc (LISTEN)
rpcbind     552    root   11u  IPv6   9106      0t0  TCP *:sunrpc (LISTEN)
rpc.statd   600   statd    9u  IPv4   9201      0t0  TCP *:44496 (LISTEN)
rpc.statd   600   statd   11u  IPv6   9207      0t0  TCP *:39888 (LISTEN)
sshd       1008    root    3u  IPv4   9856      0t0  TCP *:ssh (LISTEN)
sshd       1008    root    4u  IPv6   9858      0t0  TCP *:ssh (LISTEN)
varnishd  12086 varnish    5u  IPv4  25150      0t0  TCP *:6081 (LISTEN)
varnishd  12086 varnish    7u  IPv4  25155      0t0  TCP 127.0.0.1:6082 (LISTEN)
varnishd  12089  vcache    5u  IPv4  25150      0t0  TCP *:6081 (LISTEN)
vagrant@varnish41-ubuntu-1404:~$ sudo /usr/sbin/varnishd -a 0.0.0.0:6081 -T 127.0.0.1:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m -C -n /tmp 2>&1|head
/* ---===### include/vdef.h ###===--- */

/*-
 * Copyright (c) 2006 Verdens Gang AS
 * Copyright (c) 2012 Fastly Inc
 * Copyright (c) 2006-2015 Varnish Software AS
 * All rights reserved.
 *
 * Author: Poul-Henning Kamp <phk@phk.freebsd.dk>
 * Author: Rogier 'DocWilco' Mulhuijzen <rogier@fastly.com>
```

**Comment by denisbr** [comment] 2017-07-20 14:24
Sorry for the slow reply time here, but as this is caused by a regression in varnish it's not really a packaging bug. See https://github.com/varnishcache/varnish-cache/issues/2316

**Comment by denisbr** [comment] 2017-07-20 14:50
Hi,

The following patch to ``/etc/init.d/varnish`` will make ``service varnish restart`` work, by disabling the configtest step: 

```
--- /etc/init.d/varnish	2017-07-20 14:01:31.000000000 +0000
+++ /etc/init.d/varnish.noconfigtest	2017-07-20 14:48:24.243660909 +0000
@@ -137,12 +137,6 @@
         status_varnishd
         ;;
     restart|force-reload)
-	if status_of_proc -p "${PIDFILE}" "${DAEMON}" "${SERVICE}" 1>/dev/null; then
-	    if ! configtest; then
-		log_failure_msg "Syntax check failed, not restarting"
-		exit 1
-	    fi
-	fi
         $0 stop
         $0 start
         ;;
```

**Comment by denisbr** [comment] 2017-08-15 12:01
I'll monitor the progress of the ``-C`` issue, and if it is not fixed before the next release, likely find a workaround for this in the initscript.

**Comment by nigoroll** [comment] 2017-11-06 11:48
@denisbr any chance you could get back to this?

**Comment by denisbr** [comment] 2017-11-06 12:32
@nigoroll Yes, indeed,

**Comment by denisbr** [comment] 2017-11-06 12:38
Two suggestions on new behaviour:

1. Just remove the syntax check altogether
2. Add "CHECK_OPTS" (or better named setting) to sourced config (``/etc/default/varnish``), and configtest with that option set, so we get a different, non-conflicting, ip/port combo to bind.

@Dridi you have better suggestions?

**Comment by Dridi** [comment] 2017-11-06 12:43
Remove the syntax check and let users implement it if needed. Especially since this is the last sysv LTS from Ubuntu, and that both Debian stable and old-stable use systemd by default.

**Comment by denisbr** [comment] 2017-11-06 12:50
Closing this, next packages built will have the correct init-scripts without configtests.

**Closed by denisbr** 2017-11-06 12:50 UTC
