### ISSUE TITLE
Ensure source packages are added to the repository

### ISSUE THREAD

**Issue by fgsch** [varnishcache/pkg-varnish-cache#12] opened 2016-02-17 16:14 UTC
Debian source package for 4.1.1 was missing from repo.varnish-cache.org.
Reported on irc. I've fixed this now but we should ensure that future source packages are available.

**Comment by lkarsten** [comment] 2016-02-18 10:58
```
lkarsten@jessie:~$ apt-get source varnish
[cut]
Need to get 2,023 kB of source archives.
Get:1 http://repo.varnish-cache.org/debian/ jessie/varnish-4.1 varnish 4.1.1-1 (diff) [12.9 kB]
Get:2 http://repo.varnish-cache.org/debian/ jessie/varnish-4.1 varnish 4.1.1-1 (dsc) [1,266 B]
Get:3 http://repo.varnish-cache.org/debian/ jessie/varnish-4.1 varnish 4.1.1-1 (tar) [2,009 kB]
Fetched 2,023 kB in 0s (3,506 kB/s)
dpkg-source: warning: extracting unsigned source package (varnish_4.1.1-1.dsc)
dpkg-source: info: extracting varnish in varnish-4.1.1
dpkg-source: info: unpacking varnish_4.1.1.orig.tar.gz
dpkg-source: info: applying varnish_4.1.1-1.diff.gz
```

This is about the .orig.tar.gz, .diff.gz, .dsc and .changes files. These are artifacted by the building Jenkins job on https://jenkins.varnish-software.com/view/VC-4.1/job/varnish-4.1-deb-debian-wheezy-amd64/ . Problem should be in the deploy (publishing) job definition.

**Comment by lkarsten** [comment] 2016-02-18 11:08
Fix applied in jenkins job definition: (jenkins-config.git's 2a44aaf7)
```
-            scp ${{SIGNEDDIR}}/*.deb jenkins@depot.varnish-software.com:/srv/crap/repo.varnish-cache.org/upload/
+            scp ${{SIGNEDDIR}}/*.deb ${{SIGNEDDIR}}/*.gz ${{SIGNEDDIR}}/*.dsc jenkins@depot.varnish-software.com:/srv/crap/repo.varnish-cache.org/upload/
```

Not tested since those jobs are doing 4.1.2-beta1 packages and we don't want those in the repo. As long as `do_debsign` does what I think it does, this should be fixed.

Leaving this open until 4.1.2 so we actual get to test this.

**Comment by lkarsten** [comment] 2016-03-31 14:31
Source confirmed in place on Varnish 4.1.2:

```
lkarsten@jessie:~$ apt-get source varnish
Reading package lists... Done
Building dependency tree       
Reading state information... Done
NOTICE: 'varnish' packaging is maintained in the 'Git' version control system at:
git://github.com/varnishcache/pkg-varnish-cache.git
Need to get 2,046 kB of source archives.
Get:1 http://repo.varnish-cache.org/debian/ jessie/varnish-4.1 varnish 4.1.2-1 (diff) [12.9 kB]
Get:2 http://repo.varnish-cache.org/debian/ jessie/varnish-4.1 varnish 4.1.2-1 (dsc) [2,141 B]
Get:3 http://repo.varnish-cache.org/debian/ jessie/varnish-4.1 varnish 4.1.2-1 (tar) [2,031 kB]
Fetched 2,046 kB in 0s (4,101 kB/s)
gpgv: Signature made Mon 07 Mar 2016 07:28:59 AM EST using RSA key ID 8F2D409F
gpgv: Can't check signature: public key not found
dpkg-source: warning: failed to verify signature on ./varnish_4.1.2-1.dsc
dpkg-source: info: extracting varnish in varnish-4.1.2
dpkg-source: info: unpacking varnish_4.1.2.orig.tar.gz
dpkg-source: info: applying varnish_4.1.2-1.diff.gz
lkarsten@jessie:~$
```

**Closed by lkarsten** 2016-03-31 14:31 UTC
Labels: pending
